a.out:
	g++ -std=c++11 main.cpp characters/character.cpp characters/common.cpp characters/fresh_goblin.cpp characters/fresh_knight.cpp characters/fresh_wizard.cpp controllers/fresh_player.cpp controllers/fresh_game.cpp controllers/input_controller.cpp 	
